# This is a basic workflow to help you get started with Actions

name: Test GitHub Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run test script
      run: echo "Hello, GitHub Actions!"
